Allow manual mode only.
maxnowack/homebridge-eq3ble pull request #16
Opened 2017-12-29 16:59 UTC by m42e

This will always tell the thermostat to keep manual mode. As
HomeBridge/Siri shall controll all changes to the Temperature.

2018-03-02 09:07 UTC, maxnowack requested changes

2018-03-02 09:07 UTC, maxnowack commented on package.json
> +  "version": "1.3.3",
Please don't increment the version by yourself

2018-03-02 09:07 UTC, maxnowack commented on src/index.js
> +        manual: this.manualOnly,
Sometimes you're using `manual` and sometimes `manualOnly`. Please unify the property names. I think `manualOnly`is more clear.

2018-12-22 19:16 UTC, joshhornby commented
@maxnowack If I make the requested changes in a new PR would you accept?

2018-12-23 12:26 UTC, maxnowack commented
@joshhornby sure!

2018-12-24 12:05 UTC, joshhornby commented
@maxnowack Added a new PR https://github.com/maxnowack/homebridge-eq3ble/pull/20

2019-10-03 20:25 UTC, closed without merging